apiVersion: apps/v1
kind: Deployment
metadata:
  name: things2do-backend
  namespace: things2do
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: things2do/backend:latest
          resources:
            limits:
              memory: 200Mi
              cpu: "1"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: things2do-config
                  key: database.uri
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: things2do-backend
  namespace: things2do
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
