version: "3.9"
services:
  gateway:
    image: traefik:latest
    command:
      - --providers.docker
      - --entryPoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
  database:
    image: mongo:latest
    restart: always
    volumes:
      - datadb:/data/db
      - configdb:/data/configdb
    expose:
      - 27017
  backend:
    build:
      context: ../backend
    image: things2do/backend
    depends_on:
      - database
    restart: always
    environment:
      # This configures the backend service using runtime variables. The
      # configuration is also possible via the environment files stored in
      # the mounted volume.
      PORT: 3000
      DATABASE_URI: mongodb://database:27017/things2do
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.rule=PathPrefix(`/backend`)
      - traefik.http.routers.backend.middlewares=backend-stripprefix
      - traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/backend
  frontend:
    build:
      context: ../frontend
      args:
        # The frontend is run by the browser. Each API call is made from
        # outside of the virtual docker network and must therefore be made
        # through the gateway. Therefore, the gateway address and not the
        # address of the backend container should be specified here.
        THINGS2DO_API: http://localhost:80/backend
        # Reverse proxy prefix which must be made known to the application
        # for client-side routing and static assets.
        PUBLIC_URL: /frontend
    image: things2do/frontend
    restart: always
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.rule=PathPrefix(`/frontend`)
      - traefik.http.routers.frontend.middlewares=frontend-stripprefix
      - traefik.http.middlewares.frontend-stripprefix.stripprefix.prefixes=/frontend
volumes:
  datadb:
  configdb:
